"use client";

import { api } from "@/lib/trpc";
import { useToast } from "@/components/ui/toast";
import { BrandAsset } from "@/types";

/**
 * Custom hook for BrandAsset CRUD operations
 *
 * Generated by MultiFileGenerator
 */
export function useBrandAsset() {
  const { toast } = useToast();
  const utils = api.useUtils();

  // Query: Fetch list of brandassets
  const {
    data: brandassets,
    isLoading,
    error,
    refetch,
  } = api.brandAsset.list.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Mutation: Create BrandAsset
  const { mutate: createBrandAsset, isPending: isCreating } =
    api.brandAsset.create.useMutation({
      onSuccess: () => {
        utils.brandAsset.list.invalidate();
        toast({
          title: "Success",
          description: "BrandAsset created successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to create brandasset",
          variant: "destructive",
        });
      },
    });

  // Mutation: Update BrandAsset
  const { mutate: updateBrandAsset, isPending: isUpdating } =
    api.brandAsset.update.useMutation({
      onSuccess: () => {
        utils.brandAsset.list.invalidate();
        toast({
          title: "Success",
          description: "BrandAsset updated successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to update brandasset",
          variant: "destructive",
        });
      },
    });

  // Mutation: Delete BrandAsset
  const { mutate: deleteBrandAsset, isPending: isDeleting } =
    api.brandAsset.delete.useMutation({
      onSuccess: () => {
        utils.brandAsset.list.invalidate();
        toast({
          title: "Success",
          description: "BrandAsset deleted successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to delete brandasset",
          variant: "destructive",
        });
      },
    });

  return {
    // Data
    brandassets: brandassets ?? [],
    isLoading,
    error,

    // Actions
    createBrandAsset,
    updateBrandAsset,
    deleteBrandAsset,
    refetch,

    // Loading states
    isCreating,
    isUpdating,
    isDeleting,
  };
}
