"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { AssetDownload } from "@/types";

interface AssetDownloadFormProps {
  onSuccess?: () => void;
  initialData?: AssetDownload;
}

/**
 * AssetDownload Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function AssetDownloadForm({ onSuccess, initialData }: AssetDownloadFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createAssetDownload } = api.assetDownload.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateAssetDownload } = api.assetDownload.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateAssetDownload({ id: initialData.id, ...data });
    } else {
      createAssetDownload(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* AssetDownload Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} AssetDownload</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new assetDownload'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="brandAssetId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Brand Asset Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter brand asset id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="downloadFormat"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Download Format</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter download format"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="downloadDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Download Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter download date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="fileSize"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>File Size</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder="Enter file size"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
