"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { ContentPost } from "@/types";

interface ContentPostFormProps {
  onSuccess?: () => void;
  initialData?: ContentPost;
}

/**
 * ContentPost Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function ContentPostForm({ onSuccess, initialData }: ContentPostFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createContentPost } = api.contentPost.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateContentPost } = api.contentPost.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateContentPost({ id: initialData.id, ...data });
    } else {
      createContentPost(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* ContentPost Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} ContentPost</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new contentPost'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="brandProjectId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Brand Project Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter brand project id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="contentText"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Content Text</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter content text"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="contentTopic"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Content Topic</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter content topic"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="toneStyle"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tone Style</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter tone style"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="generationPrompt"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Generation Prompt</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter generation prompt"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="mediaAttachments"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Media Attachments</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter media attachments"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="createdDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Created Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter created date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="lastEditedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Last Edited Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter last edited date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Status</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter status"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="wasAiGenerated"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Was Ai Generated</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter was ai generated"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
