"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { ApiUsage } from "@/types";

interface ApiUsageFormProps {
  onSuccess?: () => void;
  initialData?: ApiUsage;
}

/**
 * ApiUsage Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function ApiUsageForm({ onSuccess, initialData }: ApiUsageFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createApiUsage } = api.apiUsage.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateApiUsage } = api.apiUsage.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateApiUsage({ id: initialData.id, ...data });
    } else {
      createApiUsage(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* ApiUsage Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} ApiUsage</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new apiUsage'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="apiProvider"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Api Provider</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter api provider"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="apiEndpoint"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Api Endpoint</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter api endpoint"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="requestType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Request Type</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter request type"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="tokensUsed"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tokens Used</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder="Enter tokens used"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="requestTimestamp"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Request Timestamp</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter request timestamp"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="responseStatus"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Response Status</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter response status"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="costAmount"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Cost Amount</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder="Enter cost amount"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="relatedEntityId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Related Entity Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter related entity id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
