"use client";

import { api } from "@/lib/trpc";
import { useToast } from "@/components/ui/toast";
import { SocialMediaConnection } from "@/types";

/**
 * Custom hook for SocialMediaConnection CRUD operations
 *
 * Generated by MultiFileGenerator
 */
export function useSocialMediaConnection() {
  const { toast } = useToast();
  const utils = api.useUtils();

  // Query: Fetch list of socialmediaconnections
  const {
    data: socialmediaconnections,
    isLoading,
    error,
    refetch,
  } = api.socialMediaConnection.list.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Mutation: Create SocialMediaConnection
  const { mutate: createSocialMediaConnection, isPending: isCreating } =
    api.socialMediaConnection.create.useMutation({
      onSuccess: () => {
        utils.socialMediaConnection.list.invalidate();
        toast({
          title: "Success",
          description: "SocialMediaConnection created successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to create socialmediaconnection",
          variant: "destructive",
        });
      },
    });

  // Mutation: Update SocialMediaConnection
  const { mutate: updateSocialMediaConnection, isPending: isUpdating } =
    api.socialMediaConnection.update.useMutation({
      onSuccess: () => {
        utils.socialMediaConnection.list.invalidate();
        toast({
          title: "Success",
          description: "SocialMediaConnection updated successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to update socialmediaconnection",
          variant: "destructive",
        });
      },
    });

  // Mutation: Delete SocialMediaConnection
  const { mutate: deleteSocialMediaConnection, isPending: isDeleting } =
    api.socialMediaConnection.delete.useMutation({
      onSuccess: () => {
        utils.socialMediaConnection.list.invalidate();
        toast({
          title: "Success",
          description: "SocialMediaConnection deleted successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to delete socialmediaconnection",
          variant: "destructive",
        });
      },
    });

  return {
    // Data
    socialmediaconnections: socialmediaconnections ?? [],
    isLoading,
    error,

    // Actions
    createSocialMediaConnection,
    updateSocialMediaConnection,
    deleteSocialMediaConnection,
    refetch,

    // Loading states
    isCreating,
    isUpdating,
    isDeleting,
  };
}
