"use client";

import { UserList } from "@/features/user/components/UserList";
import { useUser } from "@/features/user/hooks/useUser";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

/**
 * User Library Page
 *
 * Browse and manage all users
 * Generated by MultiFileGenerator
 */
export default function UserLibraryPage() {
  const router = useRouter();
  const [searchQuery, setSearchQuery] = useState("");

  const handleCreateClick = () => {
    router.push("/create-user");
  };

  return (
    <div className="container mx-auto p-6">
      {/* Header */}
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Users</h1>
          <p className="text-muted-foreground mt-2">
            Browse and manage your users
          </p>
        </div>

        <Button onClick={handleCreateClick}>
          <Plus className="mr-2 h-4 w-4" />
          Create User
        </Button>
      </div>

      {/* List Component */}
      <UserList
        searchQuery={searchQuery}
        onSelect={(item) => {
          // Handle item selection (could navigate to detail page)
          console.log("Selected:", item);
        }}
      />
    </div>
  );
}
