"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { BrandProject } from "@/types";

interface BrandProjectFormProps {
  onSuccess?: () => void;
  initialData?: BrandProject;
}

/**
 * BrandProject Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function BrandProjectForm({ onSuccess, initialData }: BrandProjectFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createBrandProject } = api.brandProject.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateBrandProject } = api.brandProject.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateBrandProject({ id: initialData.id, ...data });
    } else {
      createBrandProject(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* BrandProject Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} BrandProject</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new brandProject'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="projectName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Project Name</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter project name"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="companyName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Company Name</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter company name"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="companyDescription"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Company Description</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter company description"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="nameSignificance"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Name Significance</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter name significance"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="designPersonality"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Design Personality</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter design personality"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="targetAudience"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Target Audience</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter target audience"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="colorDirection"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Color Direction</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter color direction"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="typographyPreferences"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Typography Preferences</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter typography preferences"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="competitiveExamples"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Competitive Examples</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter competitive examples"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="desiredAssetTypes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Desired Asset Types</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter desired asset types"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="createdDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Created Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter created date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="lastModifiedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Last Modified Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter last modified date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="isActive"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Is Active</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter is active"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
