/**
 * Enum type definitions
 * Auto-generated from requirements
 *
 * NOTE: Entity-specific enums (from validation rules) are generated by Prisma
 * and should be imported from '@prisma/client'. This file only contains
 * application-level enums that are not tied to database entities.
 */

// ============= APPLICATION ENUMS =============

export enum AuthProvider {
  EMAIL = 'EMAIL',
  GOOGLE = 'GOOGLE',
  GITHUB = 'GITHUB',
  TWITTER = 'TWITTER'
}

// ============= ENUM UTILITIES =============

export const enumToArray = <T extends Record<string, string>>(enumObj: T): T[keyof T][] => {
  return Object.values(enumObj) as T[keyof T][]
}

export const enumToOptions = <T extends Record<string, string>>(enumObj: T) => {
  return Object.entries(enumObj).map(([key, value]) => ({
    label: key.replace(/_/g, ' ').toLowerCase().replace(/w/g, c => c.toUpperCase()),
    value: value
  }))
}