"use client";

import { useRouter } from "next/navigation";
import { api } from "@/lib/trpc";

/**
 * Authentication hook for user session management
 *
 * Generated by MultiFileGenerator
 */
export function useAuth() {
  const router = useRouter();
  const { data: user, isLoading } = api.auth.getSession.useQuery();

  const logout = () => {
    router.push("/auth/logout");
  };

  return {
    user,
    isLoading,
    isAuthenticated: !!user,
    logout,
  };
}
