"use client";

'use client'

import React, { useState, useEffect, useCallback, useMemo } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import * as z from 'zod'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useToast } from '@/components/ui/toast'
import { Loader2, Plus, Edit, Trash, Search, Filter } from 'lucide-react'
import { api as trpc } from '@/lib/trpc'
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'
import { cn } from '@/lib/utils'
import { UserList } from "@/features/user/components/UserList";
import { UserForm } from "@/features/user/components/UserForm";
import { SocialMediaConnectionList } from "@/features/social-media-connection/components/SocialMediaConnectionList";
import { SocialMediaConnectionForm } from "@/features/social-media-connection/components/SocialMediaConnectionForm";
import { BrandProjectList } from "@/features/brand-project/components/BrandProjectList";
import { BrandProjectForm } from "@/features/brand-project/components/BrandProjectForm";
import { useAuth } from "@/features/shared/hooks/useAuth";
import { redirect } from "next/navigation";

/**
 * Main dashboard page for Generated Application
 *
 * Orchestrates entity management with tab-based navigation.
 * All business logic is in feature modules (features/[entity]/)
 *
 * Generated by MultiFileGenerator - orchestration only
 */
export default function HomePage() {
  const { user, isLoading } = useAuth();

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
      </div>
    );
  }

  if (!user) {
    redirect("/auth/login");
  }

  return (
    <div className="container mx-auto p-6">
      <div className="mb-8">
        <h1 className="text-3xl font-bold">Generated Application</h1>
        <p className="text-muted-foreground mt-2">
          AI-powered platform for social media content creation, scheduling, and professional brand design assets.
        </p>
      </div>

      <Tabs defaultValue="user" className="space-y-4">
        <TabsList>
          <TabsTrigger value="user">Users</TabsTrigger>
          <TabsTrigger value="social-media-connection">SocialMediaConnections</TabsTrigger>
          <TabsTrigger value="brand-project">BrandProjects</TabsTrigger>
        </TabsList>

        <TabsContent value="user" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Create User</CardTitle>
              </CardHeader>
              <CardContent>
                <UserForm />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Your Users</CardTitle>
              </CardHeader>
              <CardContent>
                <UserList />
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="social-media-connection" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Create SocialMediaConnection</CardTitle>
              </CardHeader>
              <CardContent>
                <SocialMediaConnectionForm />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Your SocialMediaConnections</CardTitle>
              </CardHeader>
              <CardContent>
                <SocialMediaConnectionList />
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="brand-project" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            <Card>
              <CardHeader>
                <CardTitle>Create BrandProject</CardTitle>
              </CardHeader>
              <CardContent>
                <BrandProjectForm />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Your BrandProjects</CardTitle>
              </CardHeader>
              <CardContent>
                <BrandProjectList />
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
