"use client";

import { api } from "@/lib/trpc";
import { useToast } from "@/components/ui/toast";
import { ScheduledPost } from "@/types";

/**
 * Custom hook for ScheduledPost CRUD operations
 *
 * Generated by MultiFileGenerator
 */
export function useScheduledPost() {
  const { toast } = useToast();
  const utils = api.useUtils();

  // Query: Fetch list of scheduledposts
  const {
    data: scheduledposts,
    isLoading,
    error,
    refetch,
  } = api.scheduledPost.list.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Mutation: Create ScheduledPost
  const { mutate: createScheduledPost, isPending: isCreating } =
    api.scheduledPost.create.useMutation({
      onSuccess: () => {
        utils.scheduledPost.list.invalidate();
        toast({
          title: "Success",
          description: "ScheduledPost created successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to create scheduledpost",
          variant: "destructive",
        });
      },
    });

  // Mutation: Update ScheduledPost
  const { mutate: updateScheduledPost, isPending: isUpdating } =
    api.scheduledPost.update.useMutation({
      onSuccess: () => {
        utils.scheduledPost.list.invalidate();
        toast({
          title: "Success",
          description: "ScheduledPost updated successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to update scheduledpost",
          variant: "destructive",
        });
      },
    });

  // Mutation: Delete ScheduledPost
  const { mutate: deleteScheduledPost, isPending: isDeleting } =
    api.scheduledPost.delete.useMutation({
      onSuccess: () => {
        utils.scheduledPost.list.invalidate();
        toast({
          title: "Success",
          description: "ScheduledPost deleted successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to delete scheduledpost",
          variant: "destructive",
        });
      },
    });

  return {
    // Data
    scheduledposts: scheduledposts ?? [],
    isLoading,
    error,

    // Actions
    createScheduledPost,
    updateScheduledPost,
    deleteScheduledPost,
    refetch,

    // Loading states
    isCreating,
    isUpdating,
    isDeleting,
  };
}
