"use client";

import { api } from "@/lib/trpc";
import { useToast } from "@/components/ui/toast";
import { ContentOptimization } from "@/types";

/**
 * Custom hook for ContentOptimization CRUD operations
 *
 * Generated by MultiFileGenerator
 */
export function useContentOptimization() {
  const { toast } = useToast();
  const utils = api.useUtils();

  // Query: Fetch list of contentoptimizations
  const {
    data: contentoptimizations,
    isLoading,
    error,
    refetch,
  } = api.contentOptimization.list.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Mutation: Create ContentOptimization
  const { mutate: createContentOptimization, isPending: isCreating } =
    api.contentOptimization.create.useMutation({
      onSuccess: () => {
        utils.contentOptimization.list.invalidate();
        toast({
          title: "Success",
          description: "ContentOptimization created successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to create contentoptimization",
          variant: "destructive",
        });
      },
    });

  // Mutation: Update ContentOptimization
  const { mutate: updateContentOptimization, isPending: isUpdating } =
    api.contentOptimization.update.useMutation({
      onSuccess: () => {
        utils.contentOptimization.list.invalidate();
        toast({
          title: "Success",
          description: "ContentOptimization updated successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to update contentoptimization",
          variant: "destructive",
        });
      },
    });

  // Mutation: Delete ContentOptimization
  const { mutate: deleteContentOptimization, isPending: isDeleting } =
    api.contentOptimization.delete.useMutation({
      onSuccess: () => {
        utils.contentOptimization.list.invalidate();
        toast({
          title: "Success",
          description: "ContentOptimization deleted successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to delete contentoptimization",
          variant: "destructive",
        });
      },
    });

  return {
    // Data
    contentoptimizations: contentoptimizations ?? [],
    isLoading,
    error,

    // Actions
    createContentOptimization,
    updateContentOptimization,
    deleteContentOptimization,
    refetch,

    // Loading states
    isCreating,
    isUpdating,
    isDeleting,
  };
}
