"use client";

import { api } from "@/lib/trpc";
import { useToast } from "@/components/ui/toast";
import { BrandProject } from "@/types";

/**
 * Custom hook for BrandProject CRUD operations
 *
 * Generated by MultiFileGenerator
 */
export function useBrandProject() {
  const { toast } = useToast();
  const utils = api.useUtils();

  // Query: Fetch list of brandprojects
  const {
    data: brandprojects,
    isLoading,
    error,
    refetch,
  } = api.brandProject.list.useQuery(undefined, {
    staleTime: 5 * 60 * 1000, // 5 minutes
  });

  // Mutation: Create BrandProject
  const { mutate: createBrandProject, isPending: isCreating } =
    api.brandProject.create.useMutation({
      onSuccess: () => {
        utils.brandProject.list.invalidate();
        toast({
          title: "Success",
          description: "BrandProject created successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to create brandproject",
          variant: "destructive",
        });
      },
    });

  // Mutation: Update BrandProject
  const { mutate: updateBrandProject, isPending: isUpdating } =
    api.brandProject.update.useMutation({
      onSuccess: () => {
        utils.brandProject.list.invalidate();
        toast({
          title: "Success",
          description: "BrandProject updated successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to update brandproject",
          variant: "destructive",
        });
      },
    });

  // Mutation: Delete BrandProject
  const { mutate: deleteBrandProject, isPending: isDeleting } =
    api.brandProject.delete.useMutation({
      onSuccess: () => {
        utils.brandProject.list.invalidate();
        toast({
          title: "Success",
          description: "BrandProject deleted successfully",
        });
      },
      onError: (error) => {
        toast({
          title: "Error",
          description: error.message || "Failed to delete brandproject",
          variant: "destructive",
        });
      },
    });

  return {
    // Data
    brandprojects: brandprojects ?? [],
    isLoading,
    error,

    // Actions
    createBrandProject,
    updateBrandProject,
    deleteBrandProject,
    refetch,

    // Loading states
    isCreating,
    isUpdating,
    isDeleting,
  };
}
