"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { SocialMediaConnection } from "@/types";

interface SocialMediaConnectionListProps {
  searchQuery?: string;
  onSelect?: (item: SocialMediaConnection) => void;
}

/**
 * SocialMediaConnection List Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateList()
 */
export function SocialMediaConnectionList({ searchQuery, onSelect }: SocialMediaConnectionListProps) {
  const [socialmediaconnections, setSocialMediaConnections] = React.useState<SocialMediaConnection[]>([]);

  // tRPC query for fetching list
  const { data, isLoading: socialmediaconnectionsLoading, refetch } = api.socialMediaConnection.list.useQuery();

  // Update local state when data changes
  React.useEffect(() => {
    if (data) {
      setSocialMediaConnections(data as any);
    }
  }, [data]);

  // CRUD handlers
  const handleCreate = () => {
    // TODO: Open create modal
  };

  const handleEdit = (id: string) => {
    // TODO: Open edit modal with item
    const item = socialmediaconnections.find((item: any) => item.id === id);
    if (item && onSelect) {
      onSelect(item);
    }
  };

  const handleDelete = (id: string) => {
    // TODO: Confirm and delete
    if (confirm("Are you sure you want to delete this socialmediaconnection?")) {
      // Implement delete mutation
    }
  };

      {/* SocialMediaConnection List */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>SocialMediaConnections</CardTitle>
              <CardDescription>Manage your socialMediaConnections</CardDescription>
            </div>
            <Button onClick={() => handleCreate()}>
              <Plus className="mr-2 h-4 w-4" />
              Add SocialMediaConnection
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {/* Search and Filters */}
          <div className="mb-6 flex flex-col sm:flex-row gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search socialMediaConnections..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-8"
              />
            </div>
            <Button variant="outline" size="icon">
              <Filter className="h-4 w-4" />
            </Button>
          </div>

          {/* Data Table */}
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                <TableHead>Id</TableHead>
                <TableHead>User Id</TableHead>
                <TableHead>Platform</TableHead>
                <TableHead>Platform Account Id</TableHead>
                <TableHead>Platform Username</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {socialMediaConnectionsLoading ? (
                  <TableRow>
                    <TableCell colSpan={6} className="text-center">
                      <Loader2 className="mx-auto h-6 w-6 animate-spin" />
                    </TableCell>
                  </TableRow>
                ) : !socialMediaConnections || socialMediaConnections.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="text-center">
                      No socialMediaConnections found
                    </TableCell>
                  </TableRow>
                ) : (
                  socialMediaConnections.map((item) => (
                    <TableRow key={item.id}>
                      <TableCell>{item.id}</TableCell>
                  <TableCell>{item.userId}</TableCell>
                  <TableCell>{item.platform}</TableCell>
                  <TableCell>{item.platformAccountId}</TableCell>
                  <TableCell>{item.platformUsername}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => handleEdit(item.id)}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => handleDelete(item.id)}
                          >
                            <Trash className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
}
