"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { SocialMediaConnection } from "@/types";

interface SocialMediaConnectionFormProps {
  onSuccess?: () => void;
  initialData?: SocialMediaConnection;
}

/**
 * SocialMediaConnection Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function SocialMediaConnectionForm({ onSuccess, initialData }: SocialMediaConnectionFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createSocialMediaConnection } = api.socialMediaConnection.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateSocialMediaConnection } = api.socialMediaConnection.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateSocialMediaConnection({ id: initialData.id, ...data });
    } else {
      createSocialMediaConnection(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* SocialMediaConnection Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} SocialMediaConnection</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new socialMediaConnection'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="platform"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Platform</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter platform"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="platformAccountId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Platform Account Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter platform account id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="platformUsername"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Platform Username</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter platform username"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="accessToken"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Access Token</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter access token"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="refreshToken"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Refresh Token</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter refresh token"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="tokenExpiryDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Token Expiry Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter token expiry date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="connectedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Connected Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter connected date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="isActive"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Is Active</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter is active"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="lastSyncDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Last Sync Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter last sync date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
