"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { BrandAsset } from "@/types";

interface BrandAssetFormProps {
  onSuccess?: () => void;
  initialData?: BrandAsset;
}

/**
 * BrandAsset Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function BrandAssetForm({ onSuccess, initialData }: BrandAssetFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createBrandAsset } = api.brandAsset.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateBrandAsset } = api.brandAsset.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateBrandAsset({ id: initialData.id, ...data });
    } else {
      createBrandAsset(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* BrandAsset Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} BrandAsset</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new brandAsset'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="brandProjectId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Brand Project Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter brand project id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="assetType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Asset Type</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter asset type"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="assetName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Asset Name</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter asset name"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="fileUrl"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>File Url</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter file url"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="fileFormat"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>File Format</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter file format"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="generationPrompt"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Generation Prompt</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter generation prompt"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="generatedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Generated Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter generated date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="version"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Version</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder="Enter version"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="isApproved"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Is Approved</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter is approved"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="parentAssetId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Parent Asset Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter parent asset id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
