"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { ContentOptimization } from "@/types";

interface ContentOptimizationFormProps {
  onSuccess?: () => void;
  initialData?: ContentOptimization;
}

/**
 * ContentOptimization Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function ContentOptimizationForm({ onSuccess, initialData }: ContentOptimizationFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createContentOptimization } = api.contentOptimization.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateContentOptimization } = api.contentOptimization.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateContentOptimization({ id: initialData.id, ...data });
    } else {
      createContentOptimization(data);
    }
  };

  // Form setup
  const form = React.useForm({
    defaultValues: initialData || {},
  });

      {/* ContentOptimization Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} ContentOptimization</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new contentOptimization'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="userId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>User Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter user id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="originalContent"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Original Content</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter original content"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="optimizedContent"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Optimized Content</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter optimized content"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="optimizationType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Optimization Type</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter optimization type"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="targetPlatform"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Target Platform</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter target platform"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="optimizationPrompt"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Optimization Prompt</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter optimization prompt"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="optimizedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Optimized Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter optimized date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="wasAccepted"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Was Accepted</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter was accepted"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="resultingContentPostId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Resulting Content Post Id</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter resulting content post id"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
}
