"use client";

import * as React from "react";
import { useForm } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Loader2, Plus, Edit, Trash, Search, Filter } from "lucide-react";
import { api } from "@/lib/trpc";
import { User } from "@/types";

interface UserFormProps {
  onSuccess?: () => void;
  initialData?: User;
}

/**
 * User Form Component
 *
 * Generated by MultiFileGenerator using UIBuilder.generateForm()
 */
export function UserForm({ onSuccess, initialData }: UserFormProps) {
  const [isLoading, setIsLoading] = React.useState(false);
  const [isEditing] = React.useState(!!initialData);
  const [isModalOpen, setIsModalOpen] = React.useState(false);

  // tRPC mutations for create/update
  const { mutate: createUser } = api.user.create.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  const { mutate: updateUser } = api.user.update.useMutation({
    onSuccess: () => {
      setIsLoading(false);
      onSuccess?.();
    },
    onError: () => {
      setIsLoading(false);
    },
  });

  // Form submission handler
  const onSubmit = (data: any) => {
    setIsLoading(true);
    if (isEditing && initialData?.id) {
      updateUser({ id: initialData.id, ...data });
    } else {
      createUser(data);
    }
  };

  // Form setup
  const form = useForm({
    defaultValues: initialData || {},
  });

  return (
    <>
      {/* User Form */}
      <Card>
        <CardHeader>
          <CardTitle>{isEditing ? 'Edit' : 'Create'} User</CardTitle>
          <CardDescription>
            {isEditing ? 'Update the information below' : 'Fill in the details to create a new user'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter email"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Password</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter password"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="emailVerified"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Email Verified</FormLabel>
                    <FormControl>
                      <Input
                        type="checkbox"
                        placeholder="Enter email verified"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="accountCreatedDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Account Created Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter account created date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="subscriptionTier"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Subscription Tier</FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder="Enter subscription tier"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="lastLoginDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Last Login Date</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        placeholder="Enter last login date"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              
              <div className="flex justify-end space-x-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    form.reset()
                    setIsModalOpen(false)
                  }}
                >
                  Cancel
                </Button>
                <Button type="submit" disabled={isLoading}>
                  {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                  {isEditing ? 'Update' : 'Create'}
                </Button>
              </div>
            </form>
          </Form>
        </CardContent>
      </Card>
    </>
  );
}
