"use client";

import { UserForm } from "@/features/user/components/UserForm";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

/**
 * Create User Page
 *
 * Dedicated page for creating new users
 * Generated by MultiFileGenerator
 */
export default function CreateUserPage() {
  const router = useRouter();

  const handleSuccess = () => {
    // Navigate to library after successful creation
    router.push("/users");
  };

  return (
    <div className="container mx-auto p-6 max-w-4xl">
      {/* Header with back button */}
      <div className="mb-6">
        <Button
          variant="ghost"
          onClick={() => router.back()}
          className="mb-4"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back
        </Button>

        <h1 className="text-3xl font-bold">Create New User</h1>
        <p className="text-muted-foreground mt-2">
          Fill in the details below to create a new user
        </p>
      </div>

      {/* Form Card */}
      <Card>
        <CardHeader>
          <CardTitle>User Details</CardTitle>
          <CardDescription>
            Provide the information for your new user
          </CardDescription>
        </CardHeader>
        <CardContent>
          <UserForm onSuccess={handleSuccess} />
        </CardContent>
      </Card>
    </div>
  );
}
